dubbo:
  application:
    name: dubbo-demo-annotation-consumer
  protocol:
    name: dubbo
    port: 20880
    payload: 8388608
  consumer:
    timeout: 30000
server:
  port: 8082
logging:
  root: debug
spring:
  application:
    name: client